### ISSUE TITLE
关于登录的方法

### ISSUE THREAD

**Issue by XanderYe** [fzls/djc_helper#1]
登录步骤有点繁琐，可以获取二维码图片实现扫码登录的，应用id和dnf可以用同一个
appId:21000127
daid:8
已退游，这是我之前写的程序 [dnf活动助手](https://github.com/XanderYe/one-step)

**Comment by fzls** [comment]
1.0.1已经加上扫码登录和自动登录啦~目前是基于Selenium来实现相关逻辑。

之前是想着使用python实现c_login_2.js中等登录相关逻辑，但是最后被最终的签名步骤卡住了。由于代码经过混淆，无法看出所用加密方式是哪种算法，以及rsa的公钥是啥，最后就换了个思路。改用Selenium库来与浏览器交互，模拟相关操作，直接复用它的原有登录代码=、=就不用纠结这个签名问题了
