### ISSUE TITLE
闪光杯绑定角色与道聚城不同时会无限弹对话框

### ISSUE THREAD

**Issue by aur3l14no** [fzls/djc_helper#116]
1. 闪光杯角色无法重新选择
2. 通常闪光杯应该绑定史诗之路绑定的角色以追求收益最大化，这很有可能就不是道聚城绑定的角色
3. 当二者不同时，不能自动领取也就罢了，现在版本会无限提示需要绑定账号，关闭提示框后会再次弹出

暂时只能先禁掉闪光杯了，如果有时间的话，还是希望这边能修复，谢谢了

**Comment by fzls** [comment]
刚看到，把第二个√去掉即可

![image](https://user-images.githubusercontent.com/13483212/205230693-c29ca5e1-5ced-4ec2-8ba3-d20257cf4d09.png)
