### ISSUE TITLE
添加仅用于心悦固定队的小号

### ISSUE THREAD

**Issue by aur3l14no** [fzls/djc_helper#2]
由于目前默认开启所有功能，因此很不方便添加这样的小号.... 如果不管的话，又会导致脚本执行时间变长

**Comment by fzls** [comment]
把其他功能设为关闭状态就好了呀=。=

**Comment by aur3l14no** [comment]
这样版本更新的时候，还要去手动把新出现的字段改成 False，感觉有一点点麻烦

**Comment by fzls** [comment]
> 这样版本更新的时候，还要去手动把新出现的字段改成 False，感觉有一点点麻烦

那可以选择手动去心悦网站每天操作=-=

这个工具更重要的是一键和自动，运行时长其实不在考虑，只要不一次运行个几小时就好。我本地每次运行十个号，大部分功能都打开，也就二十来分钟

**Comment by aur3l14no** [comment]
ok 总之谢谢作者了
