### ISSUE TITLE
8.3.0版本执行完关闭后，chrome进程还在后台

### ISSUE THREAD

**Issue by iyinyin8** [fzls/djc_helper#4]
8.3.0版本发现问题，用简易配置工具勾选了“强制使用便携版”和“自动登录模式不显示浏览器界面”，昨晚执行完后关闭了小助手界面，今早在任务管理器里发现了内置的便携版chrome进程还在

**Comment by fzls** [comment]
=、=应该是中途登录没完成的时候就直接把关掉命令行导致的吧，如果正常登录完成，应该是会关闭的
