### ISSUE TITLE
建议默认关闭付费用户的支付宝领红包提示

### ISSUE THREAD

**Issue by wang92332** [fzls/djc_helper#42]
虽然我会折腾python，能用源码运行，但我为了支持作者还是坚持付费，但我既然已经付费了，可不可以默认不要给我弹支付宝领红包，配置里勾选过两次了，还是偶尔会弹出来。
工具很好用，但一年60的价格也已经比肩utools、Quicker、钱迹这类优秀的软件了，可不可以让我们付费用户就安安静静的使用工具。
![image](https://user-images.githubusercontent.com/22436549/144603112-1ae7f5de-b9e1-42e7-80a3-21bf27b9f7a1.png)

**Comment by fzls** [comment]
配置工具里不是有开关吗=、=

**Comment by fzls** [comment]
在小助手目录增加一个 名为 .never_show_ask_message_box 的文件或者文件夹，后续这类请求类的弹窗或直接屏蔽

![image](https://user-images.githubusercontent.com/13483212/144609578-d77db957-12f5-423e-87eb-3eeb48c8301d.png)

**Comment by fzls** [comment]
另外，你可以通过计划任务程序来自动运行，然后不点击那个确认框，就不会弹出红包二维码的= = 没出异常情况没必要点开看的
