### ISSUE TITLE
djc_helper 第 1117 行附近抛异常

### ISSUE THREAD

**Issue by aur3l14no** [fzls/djc_helper#6]
`pak_list = member.pak.split("|")` 抛出异常，因为 `member.pak` 为 False

不知道是不是我这边的问题

**Comment by fzls** [comment]
刚看了下我这边的周一的新组队日志，是有这么个问题，因为前天接入的时候，我俩号都已经手动组队并领过一次奖励了。
我处理下~
这个刚改版，前一两周估计会有各种未预期的问题

**Comment by fzls** [comment]
更新即可
