### ISSUE TITLE
笑死，别用码云了

### ISSUE THREAD

**Issue by CangShui** [fzls/djc_helper#7]
【目录名称含有违规信息】

**Comment by fzls** [comment]
=。=我本来就不用啊，就是顺带同步下给不方便访问github的朋友用哇

**Comment by fzls** [comment]
有毒，这什么鬼玩意- -去看了下，gitee还真给屏蔽了

**Comment by fzls** [comment]
哈哈，还有其他国内的托管平台吗-。-
真没有的话还是只能像之前一样让不能访问github的使用类似https://hub.fastgit.org、
https://github.com.cnpmjs.org这类镜像站了

**Comment by fzls** [comment]
试了下，似乎不影响clone哈哈哈
