### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CangShui** [fzls/djc_helper#8]
21:02:48 try_request:77  WARNI: 3/3: request failed, wait 5s。异常补充说明如下：
21:02:48 try_request:81  ERROR: 重试3次后仍失败
21:02:48 <module>:155 ERROR: ver 9.5.0 (发布于2021.4.29，距今已有1天啦) 运行过程中出现未捕获的异常，请加群743671885反馈 或自行解决。

**Comment by fzls** [comment]
- -这个是网络问题导致登录失败，建议看下在这之前提示的错误信息
