### ISSUE TITLE
程序运行后,系统会自动添加英语模式的英文键盘

### ISSUE THREAD

**Issue by u2shana** [fzls/djc_helper#88]
![image](https://user-images.githubusercontent.com/14146754/182035221-8ed54200-1bd0-44fe-b31f-e43e700a7a30.png)
困扰了我很久的问题,我就说怎么删了这键盘过段时间还会冒出来,每次打dnf时都要多切一下输入法
![image](https://user-images.githubusercontent.com/14146754/182035320-d3e1a563-8b69-49d4-8248-a0ffb78bb490.png)
今天问了别人后,自己排查下发现是蚊子腿助手引起的,源码版和打包版都会触发

**Comment by fzls** [comment]
这个之前好像有人反馈过= =但我实在想不出来是为啥
我自己使用的是英文+中文双输入法，所以一直没注意到这么回事

**Comment by u2shana** [comment]
> 这个之前好像有人反馈过= =但我实在想不出来是为啥 我自己使用的是英文+中文双输入法，所以一直没注意到这么回事

我试了下差不多是在开头进行检测的那段流程添加的键盘

**Comment by fzls** [comment]
> > 这个之前好像有人反馈过= =但我实在想不出来是为啥 我自己使用的是英文+中文双输入法，所以一直没注意到这么回事
> 
> 我试了下差不多是在开头进行检测的那段流程添加的键盘

定位了一下，好像是下面这行代码造成的-。-

https://github.com/fzls/djc_helper/blob/bb127af70c11d30a1f766828ea6fd4e128bc2766/qq_login.py#L384-L386

**Comment by fzls** [comment]
断点跟下去，在selenium的这一行执行完成后，会添加en-us的键盘布局

https://github.com/SeleniumHQ/selenium/blob/0d3887531380e0c803b555752f64c7262e8e4664/py/selenium/webdriver/remote/webdriver.py#L369

**Comment by fzls** [comment]
基本可以确定是chrome_driver.exe的问题了，selenium通过http接口来调用它创建新session的时候，它会尝试添加en-us键盘
我试了下，启动chrome_driver后，直接用postman发请求给它也能触发同样的行为

![image](https://user-images.githubusercontent.com/13483212/183371636-5230d3d0-0dfb-49a0-b986-d37aa0978703.png)

![image](https://user-images.githubusercontent.com/13483212/183371712-c283238a-ac5b-450b-bdeb-86d2a28448c3.png)

**Comment by fzls** [comment]
这个没法修-。-因为要依靠它来完成登录QQ的流程

**Comment by fzls** [comment]
附带一下重现方案

0. 在 系统设置/时间和语言/语言和区域中，在英语（美国）右侧选择删除。如果没有英语选项，但win+space中有，则先点添加语言，将英语（美国）添加后再执行删除操作即可
![image](https://user-images.githubusercontent.com/13483212/183373465-2a095c9e-0efe-4df7-8e57-353dbc30db89.png)

![image](https://user-images.githubusercontent.com/13483212/183373653-112e9c45-7c65-45d5-ac5b-158490e3ef49.png)


2. 双击utils/chromedriver_102.exe
![image](https://user-images.githubusercontent.com/13483212/183372888-abd85273-df48-414c-80dc-33366a4f8e79.png)

3. 观察上面日志显示的端口号（on port xxxx，比如上图是 9515），替换到下面这段curl指令中的端口处

```bash
curl --location --request POST 'http://localhost:9515/session' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json;charset=UTF-8' \
--header 'User-Agent: selenium/4.3.0 (python windows)' \
--header 'Connection: keep-alive' \
--data-raw '{"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"excludeSwitches": ["enable-logging"], "extensions": [], "args": ["--headless"]}}}}'
```

4. 使用github bash执行上面的curl指令，会发现多出了 英语（美国） 键盘布局
![image](https://user-images.githubusercontent.com/13483212/183373252-1c73fd84-5b14-44ab-aee0-e322e9213544.png)
