### ISSUE TITLE
dnf官方论坛签到时formhash过期导致无法正常签到

### ISSUE THREAD

**Issue by asdf12303116** [fzls/djc_helper#9]
dnf官方论坛签到时formhash过期且cookie未过期时，签到接口会返回状态为200的空body，导致签到失败。

不带formhash且cookie有效时会返回一个错误提示，body为html。

可以使用无formhash+带cookie访问一次签到接口,返回中class为logout的a标签的herf(如下)可直接获得当前有效的formhash

`<a class="logout" href="member.php?mod=logging&amp;action=logout&amp;formhash=xxxxxx">退出登陆</a>`

可使用正则`(?<=<a class=\"logout\" href=\")([^\"]*)`直接获取。

结果为`member.php?mod=logging&amp;action=logout&amp;formhash=xxxxxxxx`，在通过urllib.parse即可直接获取当前有效的formhash

**Comment by fzls** [comment]
好像这几天是过期了-。-重新去网页抓一下就好了

一次抓取基本可以用好几个月，所以也没啥必要改-。-
